spring:
datasource:
driverClassName: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/library_management
username: user
password: 123456
jpa:
hibernate.ddl-auto: update
generate-ddl: true
show-sql: true

key:
  jwtsecret: CctlD5JL16m8wLTgsFNhzqjQP
  jwtissuer: key