spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management
    username: xxxx
    password: xxxx
  jpa:
    hibernate:
    generate-ddl: true
    show-sql: true

key:
  jwtsecret: CctlD5JL16m8wLTgsFNhzqjQP
  jwtissuer: key